# Generated by Django 4.1 on 2022-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_emp_details_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='is_deleted',
            field=models.CharField(default='no', max_length=2),
        ),
    ]
