# Generated by Django 4.1 on 2022-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_emp_details_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
